[project]
name = "Ossplate"
description = "Build one project, ship it everywhere."
repository = "https://github.com/stefdevscore/ossplate"
license = "Unlicense"

[author]
name = "Stef"
email = "stefdevscore@github.com"

[packages]
rust_crate = "ossplate"
npm_package = "ossplate"
python_package = "ossplate"
command = "ossplate"
